apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fueltrack-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: fueltrack.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: fueltrack-service
                port:
                  number: 9001
