apiVersion: v1
kind: Service
metadata:
  name: fueltrack-service
  labels:
    app: fueltrack
spec:
  selector:
    app: fueltrack
  ports:
    - protocol: TCP
      port: 9001
      targetPort: 9001
