name: cicd

on:
  push:
    branches:
      - main

jobs:
# =======================
# CI JOB
# =======================
  ci:
    runs-on: ubuntu-latest

    outputs:
      image_tag: ${{ steps.tag.outputs.sha }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set short SHA
        id: tag
        run: echo "sha=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            hasino2258/fueltrack:latest
            hasino2258/fueltrack:${{ steps.tag.outputs.sha }}

# =======================
# CD JOB
# =======================
  cd:
    needs: ci
    runs-on: self-hosted

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install yq
        run: |
          sudo curl -sSL \
            https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 \
            -o /usr/local/bin/yq
          sudo chmod +x /usr/local/bin/yq
          yq --version

      - name: Update Helm values.yaml
        run: |
          echo "New image tag: ${{ needs.ci.outputs.image_tag }}"
          yq -i '.image.tag = "${{ needs.ci.outputs.image_tag }}"' charts/fueltrack/values.yaml

      - name: Commit Helm values update
        uses: EndBug/add-and-commit@v9
        with:
          message: "chore: update image tag to ${{ needs.ci.outputs.image_tag }}"
          add: "charts/fueltrack/values.yaml"

      - name: Install ArgoCD CLI
        run: |
          sudo rm -f /usr/local/bin/argocd
          curl -ksSL -o argocd \
            https://argocd-server.argocd/download/argocd-linux-amd64
          chmod +x argocd
          sudo mv argocd /usr/local/bin/argocd
          argocd version --client

      - name: ArgoCD Login
        run: |
          argocd login argocd-server.argocd \
            --insecure \
            --grpc-web \
            --username admin \
            --password ${{ secrets.ARGOCD_PASSWORD }}

      - name: Sync Application
        run: |
          argocd app sync fueltrack
